name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: esp32dev
            name: ESP32
          - board: nanoatmega328
            name: Arduino Nano
          - board: nucleo_wb55rg_p
            name: STM32 (STM32duino)

    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: pio-${{ matrix.board }}-${{ hashFiles('library.json') }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Compile examples
        env:
          # This tells PlatformIO to look for libraries in the root of the checkout
          PLATFORMIO_LIB_EXTRA_DIRS: ${{ github.workspace }}
        run: |
          # Removed --lib="."
          pio ci --board=${{ matrix.board }} examples/basic_motor_control/basic_motor_control.ino
          pio ci --board=${{ matrix.board }} examples/fault_monitoring/fault_monitoring.ino
